# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 712)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1301, 2060))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.WidgetGridLayout = QtWidgets.QGridLayout()
        self.WidgetGridLayout.setObjectName("WidgetGridLayout")
        self.AttachmentPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.AttachmentPB.setObjectName("AttachmentPB")
        self.WidgetGridLayout.addWidget(self.AttachmentPB, 10, 6, 1, 1)
        self.Attachments = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.Attachments.setMinimumSize(QtCore.QSize(300, 0))
        self.Attachments.setObjectName("Attachments")
        self.WidgetGridLayout.addWidget(self.Attachments, 4, 6, 4, 2)
        self.AttachmentsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.AttachmentsLabel.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.AttachmentsLabel.setObjectName("AttachmentsLabel")
        self.WidgetGridLayout.addWidget(self.AttachmentsLabel, 2, 6, 1, 2)
        self.BreakdownsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.BreakdownsLabel.setObjectName("BreakdownsLabel")
        self.WidgetGridLayout.addWidget(self.BreakdownsLabel, 18, 0, 1, 2)
        self.DimensionalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.DimensionalLabel.setObjectName("DimensionalLabel")
        self.WidgetGridLayout.addWidget(self.DimensionalLabel, 16, 0, 1, 2)
        self.Safety = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Safety.setMaximumSize(QtCore.QSize(16777215, 1002))
        self.Safety.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Safety.setTabChangesFocus(True)
        self.Safety.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Safety.setObjectName("Safety")
        self.WidgetGridLayout.addWidget(self.Safety, 11, 0, 1, 8)
        self.Breakdowns = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Breakdowns.setObjectName("Breakdowns")
        self.WidgetGridLayout.addWidget(self.Breakdowns, 19, 0, 1, 8)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.WidgetGridLayout.addWidget(self.label, 6, 5, 1, 1)
        self.RemoveAttachmentPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.RemoveAttachmentPB.setObjectName("RemoveAttachmentPB")
        self.WidgetGridLayout.addWidget(self.RemoveAttachmentPB, 10, 7, 1, 1)
        self.EquipRepairsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.EquipRepairsLabel.setObjectName("EquipRepairsLabel")
        self.WidgetGridLayout.addWidget(self.EquipRepairsLabel, 32, 0, 1, 2)
        self.STARTCardAuditLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.STARTCardAuditLabel.setObjectName("STARTCardAuditLabel")
        self.WidgetGridLayout.addWidget(self.STARTCardAuditLabel, 12, 0, 1, 1)
        self.EnvironmentalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.EnvironmentalLabel.setObjectName("EnvironmentalLabel")
        self.WidgetGridLayout.addWidget(self.EnvironmentalLabel, 36, 0, 1, 2)
        self.ProdTime = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.ProdTime.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ProdTime.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.ProdTime.setObjectName("ProdTime")
        self.WidgetGridLayout.addWidget(self.ProdTime, 7, 0, 1, 1)
        self.UBJPHLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.UBJPHLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.UBJPHLabel.setObjectName("UBJPHLabel")
        self.WidgetGridLayout.addWidget(self.UBJPHLabel, 6, 3, 1, 1)
        self.FollowUpLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.FollowUpLabel.setObjectName("FollowUpLabel")
        self.WidgetGridLayout.addWidget(self.FollowUpLabel, 34, 0, 1, 2)
        self.MetalJPHLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.MetalJPHLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.MetalJPHLabel.setObjectName("MetalJPHLabel")
        self.WidgetGridLayout.addWidget(self.MetalJPHLabel, 6, 4, 1, 1)
        self.TopXActionsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.TopXActionsLabel.setObjectName("TopXActionsLabel")
        self.WidgetGridLayout.addWidget(self.TopXActionsLabel, 20, 0, 1, 2)
        self.ProdTimeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ProdTimeLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.ProdTimeLabel.setFont(font)
        self.ProdTimeLabel.setObjectName("ProdTimeLabel")
        self.WidgetGridLayout.addWidget(self.ProdTimeLabel, 6, 0, 1, 1)
        self.STARTCardAudit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.STARTCardAudit.setObjectName("STARTCardAudit")
        self.WidgetGridLayout.addWidget(self.STARTCardAudit, 13, 0, 1, 8)
        self.DoorRepairs = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.DoorRepairs.setObjectName("DoorRepairs")
        self.WidgetGridLayout.addWidget(self.DoorRepairs, 31, 0, 1, 8)
        self.UBJPH = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.UBJPH.setMaximumSize(QtCore.QSize(16777215, 30))
        self.UBJPH.setObjectName("UBJPH")
        self.WidgetGridLayout.addWidget(self.UBJPH, 7, 3, 1, 1)
        self.EquipFailuresLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.EquipFailuresLabel.setObjectName("EquipFailuresLabel")
        self.WidgetGridLayout.addWidget(self.EquipFailuresLabel, 28, 0, 1, 2)
        self.Environmental = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Environmental.setObjectName("Environmental")
        self.WidgetGridLayout.addWidget(self.Environmental, 37, 0, 1, 8)
        self.EquipRepairs = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.EquipRepairs.setObjectName("EquipRepairs")
        self.WidgetGridLayout.addWidget(self.EquipRepairs, 33, 0, 1, 8)
        self.DateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.DateLabel.setObjectName("DateLabel")
        self.WidgetGridLayout.addWidget(self.DateLabel, 2, 1, 1, 2)
        self.MetalUnitsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.MetalUnitsLabel.setObjectName("MetalUnitsLabel")
        self.WidgetGridLayout.addWidget(self.MetalUnitsLabel, 6, 1, 1, 2)
        self.MaintCrew = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.MaintCrew.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MaintCrew.setObjectName("MaintCrew")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.WidgetGridLayout.addWidget(self.MaintCrew, 4, 3, 1, 1)
        self.ProdShift = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.ProdShift.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ProdShift.setObjectName("ProdShift")
        self.ProdShift.addItem("")
        self.ProdShift.addItem("")
        self.WidgetGridLayout.addWidget(self.ProdShift, 4, 4, 1, 1)
        self.Date = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Date.setMaximumSize(QtCore.QSize(16777215, 31))
        self.Date.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Date.setObjectName("Date")
        self.WidgetGridLayout.addWidget(self.Date, 4, 1, 1, 2)
        self.ManningMaterials = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.ManningMaterials.setObjectName("ManningMaterials")
        self.WidgetGridLayout.addWidget(self.ManningMaterials, 23, 0, 1, 8)
        self.SafetyLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.SafetyLabel.setObjectName("SafetyLabel")
        self.WidgetGridLayout.addWidget(self.SafetyLabel, 10, 0, 1, 1)
        self.ManningMaterialsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ManningMaterialsLabel.setObjectName("ManningMaterialsLabel")
        self.WidgetGridLayout.addWidget(self.ManningMaterialsLabel, 22, 0, 1, 2)
        self.DoorRepairsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.DoorRepairsLabel.setObjectName("DoorRepairsLabel")
        self.WidgetGridLayout.addWidget(self.DoorRepairsLabel, 30, 0, 1, 2)
        self.FollowUp = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.FollowUp.setObjectName("FollowUp")
        self.WidgetGridLayout.addWidget(self.FollowUp, 35, 0, 1, 8)
        self.TopXActions = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.TopXActions.setObjectName("TopXActions")
        self.WidgetGridLayout.addWidget(self.TopXActions, 21, 0, 1, 8)
        self.RecognitionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.RecognitionLabel.setObjectName("RecognitionLabel")
        self.WidgetGridLayout.addWidget(self.RecognitionLabel, 24, 0, 1, 2)
        self.Training = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Training.setObjectName("Training")
        self.WidgetGridLayout.addWidget(self.Training, 27, 0, 1, 8)
        self.JoiningLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.JoiningLabel.setObjectName("JoiningLabel")
        self.WidgetGridLayout.addWidget(self.JoiningLabel, 14, 0, 1, 1)
        self.NextRecordPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.NextRecordPB.setObjectName("NextRecordPB")
        self.WidgetGridLayout.addWidget(self.NextRecordPB, 5, 2, 1, 1)
        self.TrainingLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.TrainingLabel.setObjectName("TrainingLabel")
        self.WidgetGridLayout.addWidget(self.TrainingLabel, 26, 0, 1, 2)
        self.MetalUnits = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.MetalUnits.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MetalUnits.setObjectName("MetalUnits")
        self.WidgetGridLayout.addWidget(self.MetalUnits, 7, 1, 1, 2)
        self.PrevRecordPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.PrevRecordPB.setObjectName("PrevRecordPB")
        self.WidgetGridLayout.addWidget(self.PrevRecordPB, 5, 1, 1, 1)
        self.FramerJPH = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.FramerJPH.setMaximumSize(QtCore.QSize(16777215, 30))
        self.FramerJPH.setObjectName("FramerJPH")
        self.WidgetGridLayout.addWidget(self.FramerJPH, 7, 5, 1, 1)
        self.STARTAuditCount = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.STARTAuditCount.setMaximumSize(QtCore.QSize(16777215, 30))
        self.STARTAuditCount.setObjectName("STARTAuditCount")
        self.WidgetGridLayout.addWidget(self.STARTAuditCount, 4, 5, 1, 1)
        self.MetalJPH = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.MetalJPH.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MetalJPH.setObjectName("MetalJPH")
        self.WidgetGridLayout.addWidget(self.MetalJPH, 7, 4, 1, 1)
        self.STARTAuditCountLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.STARTAuditCountLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.STARTAuditCountLabel.setObjectName("STARTAuditCountLabel")
        self.WidgetGridLayout.addWidget(self.STARTAuditCountLabel, 2, 5, 1, 1)
        self.ProdShiftLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ProdShiftLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ProdShiftLabel.setObjectName("ProdShiftLabel")
        self.WidgetGridLayout.addWidget(self.ProdShiftLabel, 2, 4, 1, 1)
        self.EquipFailures = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.EquipFailures.setObjectName("EquipFailures")
        self.WidgetGridLayout.addWidget(self.EquipFailures, 29, 0, 1, 8)
        self.MaintCrewLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.MaintCrewLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.MaintCrewLabel.setObjectName("MaintCrewLabel")
        self.WidgetGridLayout.addWidget(self.MaintCrewLabel, 2, 3, 1, 1)
        self.LetterIDLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.LetterIDLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LetterIDLabel.setObjectName("LetterIDLabel")
        self.WidgetGridLayout.addWidget(self.LetterIDLabel, 2, 0, 1, 1)
        self.Joining = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Joining.setObjectName("Joining")
        self.WidgetGridLayout.addWidget(self.Joining, 15, 0, 1, 8)
        self.Dimensional = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Dimensional.setObjectName("Dimensional")
        self.WidgetGridLayout.addWidget(self.Dimensional, 17, 0, 1, 8)
        self.Recognition = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.Recognition.setObjectName("Recognition")
        self.WidgetGridLayout.addWidget(self.Recognition, 25, 0, 1, 8)
        self.LetterID = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.LetterID.setMaximumSize(QtCore.QSize(16777215, 30))
        self.LetterID.setMouseTracking(False)
        self.LetterID.setTabChangesFocus(True)
        self.LetterID.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LetterID.setObjectName("LetterID")
        self.WidgetGridLayout.addWidget(self.LetterID, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.WidgetGridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 37))
        self.menubar.setObjectName("menubar")
        self.menuNight_Letter = QtWidgets.QMenu(self.menubar)
        self.menuNight_Letter.setObjectName("menuNight_Letter")
        self.menuOption_2 = QtWidgets.QMenu(self.menuNight_Letter)
        self.menuOption_2.setObjectName("menuOption_2")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuPrint = QtWidgets.QMenu(self.menubar)
        self.menuPrint.setObjectName("menuPrint")
        self.menuDate = QtWidgets.QMenu(self.menubar)
        self.menuDate.setObjectName("menuDate")
        self.menuDown = QtWidgets.QMenu(self.menubar)
        self.menuDown.setObjectName("menuDown")
        self.menuUp = QtWidgets.QMenu(self.menubar)
        self.menuUp.setObjectName("menuUp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOption_3 = QtWidgets.QAction(MainWindow)
        self.actionOption_3.setObjectName("actionOption_3")
        self.actionOption_A = QtWidgets.QAction(MainWindow)
        self.actionOption_A.setObjectName("actionOption_A")
        self.actionOption_B = QtWidgets.QAction(MainWindow)
        self.actionOption_B.setObjectName("actionOption_B")
        self.actionStartup_Checklist = QtWidgets.QAction(MainWindow)
        self.actionStartup_Checklist.setObjectName("actionStartup_Checklist")
        self.actionRecognition = QtWidgets.QAction(MainWindow)
        self.actionRecognition.setObjectName("actionRecognition")
        self.actionStart_Card_Report = QtWidgets.QAction(MainWindow)
        self.actionStart_Card_Report.setObjectName("actionStart_Card_Report")
        self.menuOption_2.addAction(self.actionOption_A)
        self.menuOption_2.addSeparator()
        self.menuOption_2.addAction(self.actionOption_B)
        self.menuNight_Letter.addSeparator()
        self.menuNight_Letter.addAction(self.menuOption_2.menuAction())
        self.menuNight_Letter.addSeparator()
        self.menuNight_Letter.addAction(self.actionOption_3)
        self.menuNight_Letter.addSeparator()
        self.menuNight_Letter.addAction(self.actionStartup_Checklist)
        self.menuNight_Letter.addAction(self.actionRecognition)
        self.menuNight_Letter.addAction(self.actionStart_Card_Report)
        self.menubar.addAction(self.menuNight_Letter.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuPrint.menuAction())
        self.menubar.addAction(self.menuDate.menuAction())
        self.menubar.addAction(self.menuDown.menuAction())
        self.menubar.addAction(self.menuUp.menuAction())

        self.retranslateUi(MainWindow)
        self.LetterID.textChanged.connect(MainWindow.savefield)
        self.MaintCrew.currentIndexChanged['int'].connect(MainWindow.savefield)
        self.STARTAuditCount.textChanged.connect(MainWindow.savefield)
        self.ProdShift.currentIndexChanged['int'].connect(MainWindow.savefield)
        self.MetalUnits.textChanged.connect(MainWindow.savefield)
        self.ProdTime.textChanged.connect(MainWindow.savefield)
        self.MetalJPH.textChanged.connect(MainWindow.savefield)
        self.FramerJPH.textChanged.connect(MainWindow.savefield)
        self.UBJPH.textChanged.connect(MainWindow.savefield)
        self.Safety.textChanged.connect(MainWindow.savefield)
        self.STARTCardAudit.textChanged.connect(MainWindow.savefield)
        self.Joining.textChanged.connect(MainWindow.savefield)
        self.Dimensional.textChanged.connect(MainWindow.savefield)
        self.Breakdowns.textChanged.connect(MainWindow.savefield)
        self.TopXActions.textChanged.connect(MainWindow.savefield)
        self.ManningMaterials.textChanged.connect(MainWindow.savefield)
        self.Recognition.textChanged.connect(MainWindow.savefield)
        self.Training.textChanged.connect(MainWindow.savefield)
        self.EquipFailures.textChanged.connect(MainWindow.savefield)
        self.DoorRepairs.textChanged.connect(MainWindow.savefield)
        self.EquipRepairs.textChanged.connect(MainWindow.savefield)
        self.FollowUp.textChanged.connect(MainWindow.savefield)
        self.Environmental.textChanged.connect(MainWindow.savefield)
        self.Attachments.textChanged.connect(MainWindow.savefield)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Night Letter"))
        self.AttachmentPB.setText(_translate("MainWindow", "Attach..."))
        self.AttachmentsLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Attachments</span></p></body></html>"))
        self.BreakdownsLabel.setText(_translate("MainWindow", "Delivery - Breakdowns"))
        self.DimensionalLabel.setText(_translate("MainWindow", "Dimensional"))
        self.Safety.setToolTip(_translate("MainWindow", "Safety Related Incidents and Notifications"))
        self.Safety.setPlaceholderText(_translate("MainWindow", "No Issues"))
        self.label.setText(_translate("MainWindow", "Framer JPH"))
        self.RemoveAttachmentPB.setText(_translate("MainWindow", "Remove..."))
        self.EquipRepairsLabel.setText(_translate("MainWindow", "Equipment Repairs"))
        self.STARTCardAuditLabel.setText(_translate("MainWindow", "Start Card Audit"))
        self.EnvironmentalLabel.setText(_translate("MainWindow", "Environmental"))
        self.ProdTime.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.UBJPHLabel.setText(_translate("MainWindow", "Underbody JPH"))
        self.FollowUpLabel.setText(_translate("MainWindow", "Follow-Up Needed"))
        self.MetalJPHLabel.setText(_translate("MainWindow", "Metal JPH"))
        self.TopXActionsLabel.setText(_translate("MainWindow", "Top X Actions"))
        self.ProdTimeLabel.setText(_translate("MainWindow", "Prod Time"))
        self.EquipFailuresLabel.setText(_translate("MainWindow", "Equipment Failures"))
        self.DateLabel.setText(_translate("MainWindow", "Date"))
        self.MetalUnitsLabel.setText(_translate("MainWindow", "Metal Units"))
        self.MaintCrew.setItemText(0, _translate("MainWindow", "A"))
        self.MaintCrew.setItemText(1, _translate("MainWindow", "B"))
        self.MaintCrew.setItemText(2, _translate("MainWindow", "C"))
        self.MaintCrew.setItemText(3, _translate("MainWindow", "D"))
        self.ProdShift.setItemText(0, _translate("MainWindow", "A"))
        self.ProdShift.setItemText(1, _translate("MainWindow", "B"))
        self.SafetyLabel.setText(_translate("MainWindow", "Safety"))
        self.ManningMaterialsLabel.setText(_translate("MainWindow", "Manning/Materials"))
        self.DoorRepairsLabel.setText(_translate("MainWindow", "Door Repairs"))
        self.RecognitionLabel.setText(_translate("MainWindow", "Recognition"))
        self.JoiningLabel.setText(_translate("MainWindow", "Joining"))
        self.NextRecordPB.setText(_translate("MainWindow", "Next"))
        self.TrainingLabel.setText(_translate("MainWindow", "Notifications - HR - Training"))
        self.PrevRecordPB.setText(_translate("MainWindow", "Previous"))
        self.STARTAuditCountLabel.setText(_translate("MainWindow", "START Card Audits"))
        self.ProdShiftLabel.setText(_translate("MainWindow", "Prod. Crew"))
        self.MaintCrewLabel.setText(_translate("MainWindow", "Maint. Crew"))
        self.LetterIDLabel.setText(_translate("MainWindow", "Letter ID"))
        self.menuNight_Letter.setTitle(_translate("MainWindow", "Shift Letter "))
        self.menuOption_2.setTitle(_translate("MainWindow", "Shutdown Form"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuPrint.setTitle(_translate("MainWindow", "Print"))
        self.menuDate.setTitle(_translate("MainWindow", "Date"))
        self.menuDown.setTitle(_translate("MainWindow", "Down"))
        self.menuUp.setTitle(_translate("MainWindow", "Up"))
        self.actionOption_3.setText(_translate("MainWindow", "Weekend Form"))
        self.actionOption_A.setText(_translate("MainWindow", "Option A"))
        self.actionOption_B.setText(_translate("MainWindow", "Option B"))
        self.actionStartup_Checklist.setText(_translate("MainWindow", "Startup Checklist"))
        self.actionRecognition.setText(_translate("MainWindow", "Recognition"))
        self.actionStart_Card_Report.setText(_translate("MainWindow", "Start Card Report"))
