# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 767)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1128, 876))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.HorizLayoutContainer = QtWidgets.QHBoxLayout()
        self.HorizLayoutContainer.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.HorizLayoutContainer.setObjectName("HorizLayoutContainer")
        self.VertLayoutContainer = QtWidgets.QVBoxLayout()
        self.VertLayoutContainer.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.VertLayoutContainer.setContentsMargins(-1, -1, -1, 9)
        self.VertLayoutContainer.setObjectName("VertLayoutContainer")
        self.WidgetLayout1 = QtWidgets.QGridLayout()
        self.WidgetLayout1.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.WidgetLayout1.setObjectName("WidgetLayout1")
        self.PrevRecordPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.PrevRecordPB.setObjectName("PrevRecordPB")
        self.WidgetLayout1.addWidget(self.PrevRecordPB, 5, 1, 1, 1)
        self.NextRecordPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.NextRecordPB.setObjectName("NextRecordPB")
        self.WidgetLayout1.addWidget(self.NextRecordPB, 5, 2, 1, 1)
        self.LetterIDLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LetterIDLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LetterIDLabel.setObjectName("LetterIDLabel")
        self.WidgetLayout1.addWidget(self.LetterIDLabel, 2, 0, 1, 1)
        self.LetterID = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.LetterID.setMaximumSize(QtCore.QSize(16777215, 30))
        self.LetterID.setMouseTracking(False)
        self.LetterID.setTabChangesFocus(True)
        self.LetterID.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LetterID.setObjectName("LetterID")
        self.WidgetLayout1.addWidget(self.LetterID, 4, 0, 1, 1)
        self.RemoveAttachmentPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveAttachmentPB.sizePolicy().hasHeightForWidth())
        self.RemoveAttachmentPB.setSizePolicy(sizePolicy)
        self.RemoveAttachmentPB.setObjectName("RemoveAttachmentPB")
        self.WidgetLayout1.addWidget(self.RemoveAttachmentPB, 7, 7, 1, 1)
        self.AttachmentsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AttachmentsLabel.sizePolicy().hasHeightForWidth())
        self.AttachmentsLabel.setSizePolicy(sizePolicy)
        self.AttachmentsLabel.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.AttachmentsLabel.setObjectName("AttachmentsLabel")
        self.WidgetLayout1.addWidget(self.AttachmentsLabel, 2, 6, 1, 2)
        self.ProdShiftLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ProdShiftLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ProdShiftLabel.setObjectName("ProdShiftLabel")
        self.WidgetLayout1.addWidget(self.ProdShiftLabel, 2, 4, 1, 1)
        self.MaintCrewLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MaintCrewLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.MaintCrewLabel.setObjectName("MaintCrewLabel")
        self.WidgetLayout1.addWidget(self.MaintCrewLabel, 2, 3, 1, 1)
        self.STARTAuditCountLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.STARTAuditCountLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.STARTAuditCountLabel.setObjectName("STARTAuditCountLabel")
        self.WidgetLayout1.addWidget(self.STARTAuditCountLabel, 2, 5, 1, 1)
        self.STARTAuditCount = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.STARTAuditCount.setMaximumSize(QtCore.QSize(16777215, 30))
        self.STARTAuditCount.setObjectName("STARTAuditCount")
        self.WidgetLayout1.addWidget(self.STARTAuditCount, 4, 5, 1, 1)
        self.Date = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Date.setMaximumSize(QtCore.QSize(16777215, 31))
        self.Date.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.Date.setObjectName("Date")
        self.WidgetLayout1.addWidget(self.Date, 4, 1, 1, 2)
        self.DateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.DateLabel.setObjectName("DateLabel")
        self.WidgetLayout1.addWidget(self.DateLabel, 2, 1, 1, 2)
        self.ProdShift = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.ProdShift.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ProdShift.setObjectName("ProdShift")
        self.ProdShift.addItem("")
        self.ProdShift.addItem("")
        self.WidgetLayout1.addWidget(self.ProdShift, 4, 4, 1, 1)
        self.MaintCrew = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.MaintCrew.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MaintCrew.setObjectName("MaintCrew")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.MaintCrew.addItem("")
        self.WidgetLayout1.addWidget(self.MaintCrew, 4, 3, 1, 1)
        self.Attachments = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.Attachments.setMinimumSize(QtCore.QSize(300, 0))
        self.Attachments.setObjectName("Attachments")
        self.WidgetLayout1.addWidget(self.Attachments, 4, 6, 3, 2)
        self.AttachmentPB = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AttachmentPB.sizePolicy().hasHeightForWidth())
        self.AttachmentPB.setSizePolicy(sizePolicy)
        self.AttachmentPB.setObjectName("AttachmentPB")
        self.WidgetLayout1.addWidget(self.AttachmentPB, 7, 6, 1, 1)
        self.VertLayoutContainer.addLayout(self.WidgetLayout1)
        self.TextEntryArea = QtWidgets.QHBoxLayout()
        self.TextEntryArea.setObjectName("TextEntryArea")
        self.WidgetLayout2 = QtWidgets.QVBoxLayout()
        self.WidgetLayout2.setObjectName("WidgetLayout2")
        self.SafetyLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SafetyLabel.setObjectName("SafetyLabel")
        self.WidgetLayout2.addWidget(self.SafetyLabel)
        self.Safety = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Safety.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Safety.setObjectName("Safety")
        self.WidgetLayout2.addWidget(self.Safety)
        self.JoiningLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.JoiningLabel.setObjectName("JoiningLabel")
        self.WidgetLayout2.addWidget(self.JoiningLabel)
        self.Joining = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Joining.setObjectName("Joining")
        self.WidgetLayout2.addWidget(self.Joining)
        self.TrainingLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrainingLabel.setObjectName("TrainingLabel")
        self.WidgetLayout2.addWidget(self.TrainingLabel)
        self.Training = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Training.setObjectName("Training")
        self.WidgetLayout2.addWidget(self.Training)
        self.EquipRepairsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.EquipRepairsLabel.setObjectName("EquipRepairsLabel")
        self.WidgetLayout2.addWidget(self.EquipRepairsLabel)
        self.EquipRepairs = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.EquipRepairs.setObjectName("EquipRepairs")
        self.WidgetLayout2.addWidget(self.EquipRepairs)
        self.FollowUpLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.FollowUpLabel.setObjectName("FollowUpLabel")
        self.WidgetLayout2.addWidget(self.FollowUpLabel)
        self.FollowUp = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.FollowUp.setObjectName("FollowUp")
        self.WidgetLayout2.addWidget(self.FollowUp)
        self.TextEntryArea.addLayout(self.WidgetLayout2)
        self.WidgetLayout3 = QtWidgets.QVBoxLayout()
        self.WidgetLayout3.setObjectName("WidgetLayout3")
        self.TopXActionsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TopXActionsLabel.setObjectName("TopXActionsLabel")
        self.WidgetLayout3.addWidget(self.TopXActionsLabel)
        self.TopXActions = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.TopXActions.setObjectName("TopXActions")
        self.WidgetLayout3.addWidget(self.TopXActions)
        self.DimensionalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.DimensionalLabel.setObjectName("DimensionalLabel")
        self.WidgetLayout3.addWidget(self.DimensionalLabel)
        self.Dimensional = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Dimensional.setObjectName("Dimensional")
        self.WidgetLayout3.addWidget(self.Dimensional)
        self.RecognitionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.RecognitionLabel.setObjectName("RecognitionLabel")
        self.WidgetLayout3.addWidget(self.RecognitionLabel)
        self.Recognition = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Recognition.setObjectName("Recognition")
        self.WidgetLayout3.addWidget(self.Recognition)
        self.DoorRepairsLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.DoorRepairsLabel.setObjectName("DoorRepairsLabel")
        self.WidgetLayout3.addWidget(self.DoorRepairsLabel)
        self.DoorRepairs = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.DoorRepairs.setObjectName("DoorRepairs")
        self.WidgetLayout3.addWidget(self.DoorRepairs)
        self.EnvironmentalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.EnvironmentalLabel.setObjectName("EnvironmentalLabel")
        self.WidgetLayout3.addWidget(self.EnvironmentalLabel)
        self.Environmental = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.Environmental.setObjectName("Environmental")
        self.WidgetLayout3.addWidget(self.Environmental)
        self.TextEntryArea.addLayout(self.WidgetLayout3)
        self.VertLayoutContainer.addLayout(self.TextEntryArea)
        self.HorizLayoutContainer.addLayout(self.VertLayoutContainer)
        self.gridLayout_4.addLayout(self.HorizLayoutContainer, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.WidgetLayout4 = QtWidgets.QGridLayout()
        self.WidgetLayout4.setVerticalSpacing(8)
        self.WidgetLayout4.setObjectName("WidgetLayout4")
        self.GoToDate = QtWidgets.QPushButton(self.centralwidget)
        self.GoToDate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.GoToDate.setObjectName("GoToDate")
        self.WidgetLayout4.addWidget(self.GoToDate, 0, 0, 1, 1)
        self.ReportsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReportsButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ReportsButton.setObjectName("ReportsButton")
        self.WidgetLayout4.addWidget(self.ReportsButton, 0, 2, 1, 1)
        self.PrintButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrintButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.PrintButton.setObjectName("PrintButton")
        self.WidgetLayout4.addWidget(self.PrintButton, 0, 1, 1, 1)
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.SearchButton.setObjectName("SearchButton")
        self.WidgetLayout4.addWidget(self.SearchButton, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.WidgetLayout4.addItem(spacerItem, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.WidgetLayout4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOption_3 = QtWidgets.QAction(MainWindow)
        self.actionOption_3.setObjectName("actionOption_3")
        self.actionOption_A = QtWidgets.QAction(MainWindow)
        self.actionOption_A.setObjectName("actionOption_A")
        self.actionOption_B = QtWidgets.QAction(MainWindow)
        self.actionOption_B.setObjectName("actionOption_B")
        self.actionStartup_Checklist = QtWidgets.QAction(MainWindow)
        self.actionStartup_Checklist.setObjectName("actionStartup_Checklist")
        self.actionRecognition = QtWidgets.QAction(MainWindow)
        self.actionRecognition.setObjectName("actionRecognition")
        self.actionStart_Card_Report = QtWidgets.QAction(MainWindow)
        self.actionStart_Card_Report.setObjectName("actionStart_Card_Report")
        self.actionSTART_Card_Audit_Report = QtWidgets.QAction(MainWindow)
        self.actionSTART_Card_Audit_Report.setObjectName("actionSTART_Card_Audit_Report")
        self.actionRecognition_Report = QtWidgets.QAction(MainWindow)
        self.actionRecognition_Report.setObjectName("actionRecognition_Report")

        self.retranslateUi(MainWindow)
        self.EquipRepairs.textChanged.connect(MainWindow.savefield)
        self.Environmental.textChanged.connect(MainWindow.savefield)
        self.DoorRepairs.textChanged.connect(MainWindow.savefield)
        self.Recognition.textChanged.connect(MainWindow.savefield)
        self.FollowUp.textChanged.connect(MainWindow.savefield)
        self.Training.textChanged.connect(MainWindow.savefield)
        self.STARTAuditCount.textChanged.connect(MainWindow.savefield)
        self.ProdShift.currentIndexChanged['int'].connect(MainWindow.savefield)
        self.MaintCrew.currentIndexChanged['int'].connect(MainWindow.savefield)
        self.Dimensional.textChanged.connect(MainWindow.savefield)
        self.TopXActions.textChanged.connect(MainWindow.savefield)
        self.LetterID.textChanged.connect(MainWindow.savefield)
        self.Joining.textChanged.connect(MainWindow.savefield)
        self.Attachments.textChanged.connect(MainWindow.savefield)
        self.Safety.textChanged.connect(MainWindow.savefield)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Night Letter"))
        self.PrevRecordPB.setText(_translate("MainWindow", "Previous"))
        self.NextRecordPB.setText(_translate("MainWindow", "Next"))
        self.LetterIDLabel.setText(_translate("MainWindow", "Letter ID"))
        self.RemoveAttachmentPB.setText(_translate("MainWindow", "Remove..."))
        self.AttachmentsLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Attachments</span></p></body></html>"))
        self.ProdShiftLabel.setText(_translate("MainWindow", "Prod. Crew"))
        self.MaintCrewLabel.setText(_translate("MainWindow", "Maint. Crew"))
        self.STARTAuditCountLabel.setText(_translate("MainWindow", "START Card Audits"))
        self.DateLabel.setText(_translate("MainWindow", "Date"))
        self.ProdShift.setItemText(0, _translate("MainWindow", "A"))
        self.ProdShift.setItemText(1, _translate("MainWindow", "B"))
        self.MaintCrew.setItemText(0, _translate("MainWindow", "A"))
        self.MaintCrew.setItemText(1, _translate("MainWindow", "B"))
        self.MaintCrew.setItemText(2, _translate("MainWindow", "C"))
        self.MaintCrew.setItemText(3, _translate("MainWindow", "D"))
        self.AttachmentPB.setText(_translate("MainWindow", "Attach..."))
        self.SafetyLabel.setText(_translate("MainWindow", "Safety"))
        self.Safety.setPlaceholderText(_translate("MainWindow", "No Issues"))
        self.JoiningLabel.setText(_translate("MainWindow", "Joining"))
        self.TrainingLabel.setText(_translate("MainWindow", "Notifications - HR - Training"))
        self.EquipRepairsLabel.setText(_translate("MainWindow", "Equipment Failures/Repairs"))
        self.FollowUpLabel.setText(_translate("MainWindow", "Follow-Up Needed"))
        self.TopXActionsLabel.setText(_translate("MainWindow", "Top X Actions"))
        self.DimensionalLabel.setText(_translate("MainWindow", "Dimensional"))
        self.RecognitionLabel.setText(_translate("MainWindow", "Recognition"))
        self.DoorRepairsLabel.setText(_translate("MainWindow", "Door Repairs"))
        self.EnvironmentalLabel.setText(_translate("MainWindow", "Environmental"))
        self.GoToDate.setText(_translate("MainWindow", "Go to Date"))
        self.ReportsButton.setText(_translate("MainWindow", "Reports"))
        self.PrintButton.setText(_translate("MainWindow", "Print"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.actionOption_3.setText(_translate("MainWindow", "Weekend Form"))
        self.actionOption_A.setText(_translate("MainWindow", "Option A"))
        self.actionOption_B.setText(_translate("MainWindow", "Option B"))
        self.actionStartup_Checklist.setText(_translate("MainWindow", "Startup Checklist"))
        self.actionRecognition.setText(_translate("MainWindow", "Recognition"))
        self.actionStart_Card_Report.setText(_translate("MainWindow", "Start Card Report"))
        self.actionSTART_Card_Audit_Report.setText(_translate("MainWindow", "START Card Audit"))
        self.actionRecognition_Report.setText(_translate("MainWindow", "Recognition"))
